cases:
  - id: QA_000
    name: Hellow word
    question: "Hi"
    file: null
    expected:
      type: keyword
      values: [我是]
      match_mode: all
    stream:
      protocol: sse
    timeout_seconds: 120000
  - id: QA_001
    name: Zain Interface Specification Document(Kofax)_V0.3 7.1章节
    question: "根据文档7.1章节生成接口"
    file: Zain Interface Specification Document(Kofax)_V0.3.docx
    expected:
      type: keyword
      values: [东京]
      match_mode: all
    stream:
      protocol: sse
    timeout_seconds: 7200
  - id: QA_002
    name: Zain Interface Specification Document(Kofax)_V0.3 全量生成
    question: "根据文档生成接口"
    file: Zain Interface Specification Document(Kofax)_V0.3.docx
    expected:
      type: regex 
      values: ["(^|[^0-9])2([^0-9]|$)"]
    stream:
      protocol: sse
    timeout_seconds: 7200
